import type {
  Exercise,
  Template,
  EquipItem,
  EquipKey,
  Pattern,
} from "@/lib/types";

/* ===================== Übungsbibliothek ===================== */
/* req-Token: none | weight(db|kb|bar) | EquipKey — Alt-Tokens dumbbell/kettlebell
 * werden in reqOk auf db/kb aliast. Jede Übung trägt ihren Muskel EXPLIZIT
 * (muscle/muscleSecondary) — muscleOf leitet nichts mehr ab. */
export const LIB: Exercise[] = [
  /* ── SQUAT — Kniebeuge-Muster ── */
  { id: "goblet", name: "Goblet Squat", pattern: "squat", tag: "Beine", req: ["weight"], weighted: true, sets: 3, repLow: 10, repHigh: 12, unit: "Wdh", muscle: "quads", muscleSecondary: "glutes", cue: "Gewicht vor der Brust, Oberkörper aufrecht, Core fest.",
    steps: ["Gewicht mit beiden Händen vor der Brust halten.", "Gesäß nach hinten und runter, Knie folgen den Zehen.", "Bis Oberschenkel waagerecht, aus den Fersen hoch."], back: "Brust offen, aufrecht, Mitte fest. Grüne Linie gerade.", easier: "Halbe Tiefe oder ohne Gewicht." },
  { id: "squat_bw", name: "Kniebeuge (Körpergewicht)", pattern: "squat", tag: "Beine", req: ["none"], weighted: false, sets: 3, repLow: 15, repHigh: 25, unit: "Wdh", muscle: "quads", muscleSecondary: "glutes", cue: "Aufrecht, langsam runter, Spannung halten.",
    steps: ["Schulterbreiter Stand, Arme vor.", "Tief und kontrolliert beugen, aufrecht bleiben.", "Aus den Fersen hoch."], back: "Rumpf fest, Rücken gerade.", easier: "Weniger tief, an Stuhllehne festhalten." },
  { id: "squat_bar", name: "Langhantel-Kniebeuge", pattern: "squat", tag: "Beine", req: ["bar"], weighted: true, sets: 3, repLow: 5, repHigh: 8, unit: "Wdh", muscle: "quads", muscleSecondary: "glutes", cue: "Stange auf dem oberen Rücken, Core hart, Brust auf.",
    steps: ["Stange auf dem Trapez, schulterbreiter Stand.", "Hüfte zurück und runter, Knie über den Zehen.", "Bis Oberschenkel waagerecht, aus den Fersen hoch."], back: "Rumpf hart anspannen, Rücken neutral, nicht rund werden.", easier: "Weniger Gewicht, Kniebeuge zur Box." },
  { id: "front_squat", name: "Frontkniebeuge (Langhantel)", pattern: "squat", tag: "Beine", req: ["bar"], weighted: true, sets: 3, repLow: 5, repHigh: 8, unit: "Wdh", muscle: "quads", muscleSecondary: "core", cue: "Stange auf den vorderen Schultern, Ellbogen hoch, aufrechter als beim Back Squat.",
    steps: ["Stange vorne ablegen, Ellbogen nach vorn-oben.", "Aufrecht runter, Knie weit nach vorn erlaubt.", "Aus der Mitte des Fußes hoch, Ellbogen bleiben oben."], back: "Sehr aufrecht — rückenfreundlicher als die Nacken-Variante.", easier: "Goblet Squat mit Kurzhantel." },
  { id: "squat_db", name: "Kurzhantel-Kniebeuge", pattern: "squat", tag: "Beine", req: ["db"], weighted: true, sets: 3, repLow: 8, repHigh: 12, unit: "Wdh", muscle: "quads", muscleSecondary: "glutes", cue: "Hanteln seitlich neben dem Körper, aufrecht beugen.",
    steps: ["Hanteln hängen seitlich, Stand schulterbreit.", "Hüfte zurück und runter, Brust auf.", "Aus den Fersen hoch, oben Po anspannen."], back: "Aufrecht bleiben, Gewichte ziehen nicht nach vorn.", easier: "Leichter oder Goblet-Haltung." },
  { id: "box_squat", name: "Kniebeuge zur Box", pattern: "squat", tag: "Beine", req: ["bar", "box"], weighted: true, sets: 3, repLow: 6, repHigh: 10, unit: "Wdh", muscle: "quads", muscleSecondary: "glutes", cue: "Kontrolliert zur Box setzen, kurz tippen, kraftvoll hoch.",
    steps: ["Box hinter dir auf Kniehöhe.", "Hüfte zurück, kontrolliert absetzen — nicht plumpsen.", "Ohne Schwung aus den Fersen hoch."], back: "Die Box begrenzt die Tiefe — gut für sichere Technik.", easier: "Höhere Box, nur Körpergewicht." },
  { id: "leg_press", name: "Beinpresse", pattern: "squat", tag: "Beine", req: ["machine"], weighted: true, sets: 3, repLow: 8, repHigh: 12, unit: "Wdh", muscle: "quads", muscleSecondary: "glutes", cue: "Füße mittig, unterer Rücken bleibt am Polster.",
    steps: ["Füße schulterbreit auf die Platte.", "Kontrolliert beugen bis ~90°, Rücken bleibt anliegen.", "Kraftvoll strecken, Knie nicht ganz durchdrücken."], back: "Po und Lende nicht vom Polster abheben lassen.", easier: "Weniger Gewicht, kleinerer Weg." },
  { id: "hack_squat", name: "Hack Squat (Maschine)", pattern: "squat", tag: "Beine", req: ["machine"], weighted: true, sets: 3, repLow: 8, repHigh: 12, unit: "Wdh", muscle: "quads", muscleSecondary: "glutes", cue: "Rücken fest ans Polster, tief und kontrolliert.",
    steps: ["Schultern unter die Polster, Füße mittig.", "Tief beugen, Rücken bleibt ganzflächig anliegen.", "Aus den Fersen hochdrücken."], back: "Die Maschine führt — Rücken bleibt entlastet am Polster.", easier: "Weniger Gewicht, halber Weg." },
  { id: "leg_extension", name: "Beinstrecker (Maschine)", pattern: "squat", tag: "Oberschenkel", req: ["machine"], weighted: true, sets: 3, repLow: 12, repHigh: 15, unit: "Wdh", muscle: "quads", cue: "Langsam strecken, oben kurz halten, langsam ablassen.",
    steps: ["Schienbeine hinter die Rolle, Rücken anlehnen.", "Beine strecken, oben 1 s anspannen.", "Kontrolliert zurück, nicht fallen lassen."], back: "Sitzposition stabil, kein Hohlkreuz beim Strecken.", easier: "Weniger Gewicht, einzelne Beine." },
  { id: "wall_sit", name: "Wandsitz", pattern: "squat", tag: "Beine", req: ["none"], weighted: false, sets: 3, repLow: 30, repHigh: 60, unit: "Sek", muscle: "quads", cue: "Rücken flach an der Wand, Knie im rechten Winkel, halten.",
    steps: ["Rücken an die Wand, Füße einen Schritt vor.", "Abrutschen bis Oberschenkel waagerecht.", "Position halten, ruhig atmen."], back: "Ganzer Rücken bleibt an der Wand — sehr rückenfreundlich.", easier: "Höher sitzen (stumpferer Kniewinkel)." },

  /* ── LUNGE — einbeinige Muster ── */
  { id: "bss", name: "Bulgarian Split Squat", pattern: "lunge", tag: "Beine", req: ["box"], weighted: true, sets: 3, repLow: 8, repHigh: 10, unit: "Wdh", muscle: "quads", muscleSecondary: "glutes", cue: "Hinterer Fuß erhöht, Rumpf aufrecht. Pro Bein.",
    steps: ["Hinterer Fuß erhöht hinter dir.", "Vorderes Bein beugen, Knie über dem Fuß.", "Aus der Ferse hoch. Seite wechseln."], back: "Aufrecht, nur leicht aus der Hüfte geneigt.", easier: "Ohne Gewicht, kleinere Schrittlänge." },
  { id: "reverse_lunge", name: "Ausfallschritt rückwärts", pattern: "lunge", tag: "Beine", req: ["none"], weighted: true, sets: 3, repLow: 8, repHigh: 12, unit: "Wdh", muscle: "quads", muscleSecondary: "glutes", cue: "Schritt zurück, Rumpf aufrecht. Pro Bein.",
    steps: ["Aus dem Stand einen Schritt nach hinten.", "Hinteres Knie Richtung Boden, vorne stabil.", "Zurück in den Stand. Seite wechseln."], back: "Oberkörper aufrecht, nicht nach vorne kippen.", easier: "Ohne Gewicht, kleinere Schritte." },
  { id: "stepup", name: "Step-ups", pattern: "lunge", tag: "Beine", req: ["box"], weighted: true, sets: 3, repLow: 10, repHigh: 12, unit: "Wdh", muscle: "quads", muscleSecondary: "glutes", cue: "Auf stabile Erhöhung, Kraft aus der Ferse. Pro Bein.",
    steps: ["Ganzen Fuß auf die Stufe.", "Über die Ferse hochsteigen.", "Kontrolliert absteigen. Seite wechseln."], back: "Aufrecht, nicht nach vorne kippen.", easier: "Niedrigere Stufe, ohne Gewicht." },
  { id: "walking_lunge", name: "Gehende Ausfallschritte", pattern: "lunge", tag: "Beine", req: ["db"], weighted: true, sets: 3, repLow: 10, repHigh: 12, unit: "Wdh", muscle: "quads", muscleSecondary: "glutes", cue: "Große Schritte nach vorn, Hanteln seitlich. Pro Bein.",
    steps: ["Weiter Schritt nach vorn, Knie Richtung Boden.", "Über die vordere Ferse hoch und direkt weiter.", "Gleichmäßiger Rhythmus, Rumpf aufrecht."], back: "Aufrecht gehen, Schritte kontrolliert setzen.", easier: "Ohne Gewicht, auf der Stelle wechseln." },
  { id: "split_squat", name: "Split Squat (statisch)", pattern: "lunge", tag: "Beine", req: ["db"], weighted: true, sets: 3, repLow: 8, repHigh: 12, unit: "Wdh", muscle: "quads", muscleSecondary: "glutes", cue: "Schrittstellung halten, senkrecht auf und ab. Pro Bein.",
    steps: ["Weite Schrittstellung einnehmen.", "Hinteres Knie senkrecht Richtung Boden.", "Hoch, Position halten — erst nach dem Satz wechseln."], back: "Rumpf aufrecht, Becken gerade.", easier: "Ohne Gewicht, an etwas festhalten." },
  { id: "side_lunge", name: "Seitlicher Ausfallschritt", pattern: "lunge", tag: "Beine", req: ["none"], weighted: true, sets: 3, repLow: 8, repHigh: 12, unit: "Wdh", muscle: "quads", muscleSecondary: "glutes", cue: "Großer Schritt zur Seite, Gegenbein gestreckt. Pro Seite.",
    steps: ["Weiten Schritt zur Seite setzen.", "In das Standbein setzen, anderes Bein gestreckt.", "Kraftvoll zurück in die Mitte."], back: "Brust auf, Gesäß nach hinten — nicht einrunden.", easier: "Kleinerer Schritt, an etwas festhalten." },
  { id: "cossack", name: "Cossack Squat", pattern: "lunge", tag: "Beine & Mobilität", req: ["none"], weighted: false, sets: 3, repLow: 6, repHigh: 10, unit: "Wdh", muscle: "quads", muscleSecondary: "glutes", cue: "Tief über ein Bein, das andere gestreckt, Ferse unten. Pro Seite.",
    steps: ["Sehr breiter Stand.", "Tief über eine Seite absetzen, Fuß bleibt flach.", "Hoch und zur anderen Seite wechseln."], back: "So aufrecht wie möglich, Tiefe langsam steigern.", easier: "Weniger tief, Hände als Gegengewicht vorhalten." },
  { id: "pistol_box", name: "Einbeinige Kniebeuge zur Box", pattern: "lunge", tag: "Beine", req: ["box"], weighted: false, sets: 3, repLow: 5, repHigh: 8, unit: "Wdh", muscle: "quads", muscleSecondary: "glutes", cue: "Auf einem Bein kontrolliert zur Box setzen. Pro Bein.",
    steps: ["Vor die Box stellen, ein Bein anheben.", "Langsam absetzen — leicht antippen.", "Ohne Schwung wieder hoch."], back: "Rumpf fest, Knie bleibt über dem Fuß.", easier: "Höhere Box, Arme nach vorn strecken." },

  /* ── HINGE — Hüft-Muster ── */
  { id: "glutebridge", name: "Glute Bridge mit Gewicht", pattern: "hinge", tag: "Gesäß", req: ["weight"], weighted: true, sets: 3, repLow: 12, repHigh: 15, unit: "Wdh", muscle: "glutes", muscleSecondary: "hamstrings", cue: "Schultern am Boden, Hüfte hoch, oben anspannen.",
    steps: ["Auf den Rücken, Füße hüftbreit auf.", "Gewicht auf der Hüfte halten.", "Hüfte hoch bis Schulter-Hüfte-Knie eine Linie."], back: "Kraft aus dem Po, nicht aus dem Rücken. Nicht überstrecken.", easier: "Nur Körpergewicht." },
  { id: "hip_thrust", name: "Hip Thrust", pattern: "hinge", tag: "Gesäß", req: ["weight", "box"], weighted: true, sets: 3, repLow: 10, repHigh: 15, unit: "Wdh", muscle: "glutes", muscleSecondary: "hamstrings", cue: "Schultern auf Box, Hüfte voll strecken.",
    steps: ["Schultern an Box/Sofa anlehnen.", "Gewicht auf der Hüfte.", "Hüfte hoch bis voll gestreckt, oben halten."], back: "Bewegung aus dem Po, Rippen unten lassen.", easier: "Ohne Gewicht oder kleinere Auflage." },
  { id: "rdl_db", name: "Rumänisches KH-Kreuzheben (leicht)", pattern: "hinge", tag: "Beinrückseite", req: ["dumbbell"], weighted: true, sets: 3, repLow: 10, repHigh: 12, unit: "Wdh", muscle: "hamstrings", muscleSecondary: "glutes", cue: "Hüfte zurück, Rücken absolut gerade, leicht bleiben.", backCaution: true,
    steps: ["Leichte Hanteln vor den Oberschenkeln.", "Hüfte nach hinten schieben, Knie leicht gebeugt.", "Bis Dehnung in den Beinrückseiten, dann zurück."], back: "Rücken kompromisslos gerade, nicht rund. Bei Reizung weglassen.", easier: "Sehr leicht, geringere Tiefe." },
  { id: "deadlift", name: "Kreuzheben (Langhantel)", pattern: "hinge", tag: "Beinrückseite & Rücken", req: ["bar"], weighted: true, sets: 3, repLow: 4, repHigh: 6, unit: "Wdh", muscle: "hamstrings", muscleSecondary: "back", cue: "Rücken absolut gerade, Stange nah am Körper, aus den Beinen ziehen.", backCaution: true,
    steps: ["Mittelfuß unter der Stange, Schienbein nah dran.", "Brust raus, Rücken neutral, Stange greifen.", "Boden wegdrücken, Stange eng hochziehen, oben Hüfte strecken."], back: "Kompromisslos gerader Rücken. Bei Rückenreizung weglassen.", easier: "Leichter oder aus erhöhter Position (Rack Pull)." },
  { id: "rdl_bar", name: "Rumänisches Kreuzheben (Langhantel)", pattern: "hinge", tag: "Beinrückseite", req: ["bar"], weighted: true, sets: 3, repLow: 6, repHigh: 10, unit: "Wdh", muscle: "hamstrings", muscleSecondary: "glutes", cue: "Hüfte weit zurück, Stange nah, Rücken gerade.", backCaution: true,
    steps: ["Stange vor den Oberschenkeln, Knie leicht gebeugt.", "Hüfte nach hinten schieben, Stange am Bein entlang.", "Bis Dehnung der Beinrückseite, dann Hüfte nach vorne."], back: "Rücken gerade, nicht rund. Bei Reizung weglassen.", easier: "Kurzhanteln, geringere Tiefe." },
  { id: "kb_swing", name: "Kettlebell Swing", pattern: "hinge", tag: "Gesäß & Beinrückseite", req: ["kb"], weighted: true, sets: 3, repLow: 12, repHigh: 15, unit: "Wdh", muscle: "glutes", muscleSecondary: "hamstrings", cue: "Kraft aus der Hüfte — die Arme schwingen nur mit.", backCaution: true,
    steps: ["Kettlebell mit beiden Händen, Hüfte zurück.", "Hüfte explosiv strecken — die Kugel schwingt bis Brusthöhe.", "Zurückschwingen lassen, wieder aus der Hüfte."], back: "Rücken bleibt gerade — die Hüfte arbeitet, nicht die Lende.", easier: "Leichtere Kugel, Deadlift-Swings (absetzen)." },
  { id: "good_morning", name: "Good Morning (Langhantel)", pattern: "hinge", tag: "Beinrückseite", req: ["bar"], weighted: true, sets: 3, repLow: 8, repHigh: 10, unit: "Wdh", muscle: "hamstrings", muscleSecondary: "glutes", cue: "Leicht bleiben: Stange im Nacken, Hüfte weit zurück.", backCaution: true,
    steps: ["Stange wie zur Kniebeuge auflegen, Knie leicht gebeugt.", "Hüfte nach hinten, Oberkörper senkt sich gerade ab.", "Bis Dehnung hinten, dann Hüfte nach vorn strecken."], back: "Nur mit tadelloser Technik und wenig Gewicht — sonst weglassen.", easier: "Ohne Stange, Hände hinterm Kopf." },
  { id: "rdl_single", name: "Einbeiniges Kreuzheben (KH)", pattern: "hinge", tag: "Beinrückseite & Balance", req: ["db"], weighted: true, sets: 3, repLow: 8, repHigh: 10, unit: "Wdh", muscle: "hamstrings", muscleSecondary: "glutes", cue: "Standbein leicht gebeugt, Hüfte kippt, Rücken lang. Pro Bein.", backCaution: true,
    steps: ["Hantel in einer Hand, Gegenbein hebt nach hinten.", "Oberkörper senkt sich, Rücken bleibt lang.", "Aus der Hüfte zurück in den Stand."], back: "Becken gerade halten, nicht aufdrehen.", easier: "Freie Hand aufstützen, weniger tief." },
  { id: "sumo_deadlift", name: "Sumo-Kreuzheben", pattern: "hinge", tag: "Gesäß & Beine", req: ["bar"], weighted: true, sets: 3, repLow: 4, repHigh: 6, unit: "Wdh", muscle: "glutes", muscleSecondary: "hamstrings", cue: "Breiter Stand, aufrechter Rumpf, Stange sehr nah.", backCaution: true,
    steps: ["Sehr breiter Stand, Zehen leicht nach außen.", "Innen greifen, Brust auf, Rücken neutral.", "Boden wegdrücken, Hüfte und Knie zusammen strecken."], back: "Aufrechter als klassisches Kreuzheben — trotzdem: neutraler Rücken.", easier: "Leichter, Kettlebell zwischen den Beinen." },
  { id: "leg_curl", name: "Beinbeuger (Maschine)", pattern: "hinge", tag: "Beinrückseite", req: ["machine"], weighted: true, sets: 3, repLow: 10, repHigh: 15, unit: "Wdh", muscle: "hamstrings", cue: "Ferse zum Po ziehen, langsam zurück.",
    steps: ["Rolle an die Fersen legen (liegend oder sitzend).", "Beugen bis kurz vor den Po.", "Langsam und kontrolliert strecken."], back: "Hüfte bleibt am Polster, kein Hohlkreuz.", easier: "Weniger Gewicht, einbeinig nachhelfen." },
  { id: "back_ext", name: "Rückenstrecker (Maschine/Bank)", pattern: "hinge", tag: "Unterer Rücken", req: ["machine"], weighted: true, sets: 3, repLow: 10, repHigh: 15, unit: "Wdh", muscle: "back", muscleSecondary: "glutes", cue: "Ruhig auf und ab, oben nicht überstrecken.", backCaution: true,
    steps: ["Hüfte auf das Polster, Füße fixieren.", "Oberkörper kontrolliert absenken.", "Bis in die Gerade aufrichten — nicht darüber hinaus."], back: "Stärkt den Rückenstrecker — nur schmerzfrei und ohne Schwung.", easier: "Ohne Zusatzgewicht, kleinerer Weg." },
  { id: "pull_through", name: "Pull-Through am Kabel", pattern: "hinge", tag: "Gesäß", req: ["cable"], weighted: true, sets: 3, repLow: 12, repHigh: 15, unit: "Wdh", muscle: "glutes", muscleSecondary: "hamstrings", cue: "Rückwärts zum Kabel, Seil zwischen den Beinen, Hüfte streckt.", backCaution: true,
    steps: ["Seil tief einhängen, rückwärts hinstellen.", "Hüfte zurückschieben, Seil zwischen den Beinen.", "Hüfte nach vorn strecken, Po fest."], back: "Sanfte Hinge-Schule — Rücken bleibt neutral, Zug macht das Kabel.", easier: "Weniger Gewicht, kleinerer Weg." },

  /* ── HPUSH — horizontales Drücken ── */
  { id: "floorpress", name: "Kurzhantel Floor Press", pattern: "hpush", tag: "Brust", req: ["dumbbell"], weighted: true, sets: 3, repLow: 8, repHigh: 12, unit: "Wdh", muscle: "chest", muscleSecondary: "triceps", cue: "Rücken flach am Boden, Oberarme tippen auf, kein Hohlkreuz.",
    steps: ["Rücken flach, Knie gebeugt, Füße auf.", "Hanteln über der Brust.", "Absenken bis Oberarme aufsetzen, dann hoch."], back: "Unterer Rücken am Boden, kein Hohlkreuz.", easier: "Leichter, langsamer absenken." },
  { id: "pushup", name: "Liegestütze", pattern: "hpush", tag: "Brust", req: ["none"], weighted: false, sets: 3, repLow: 8, repHigh: 15, unit: "Wdh", muscle: "chest", muscleSecondary: "triceps", cue: "Körper als Brett, Core fest.",
    steps: ["Hände schulterbreit, Körper gerade.", "Absenken bis Brust knapp über Boden.", "Hochdrücken."], back: "Po anspannen, Hüfte nicht durchhängen.", easier: "Knie absetzen oder Hände erhöht." },
  { id: "dips", name: "Dips an den Ringen", pattern: "hpush", tag: "Brust", req: ["rings"], weighted: false, sets: 3, repLow: 6, repHigh: 10, unit: "Wdh", muscle: "chest", muscleSecondary: "triceps", cue: "Ringe eng am Körper, oben leicht ausdrehen, Core fest.",
    steps: ["In den Stütz drücken, Arme gestreckt, Ringe leicht ausgedreht.", "Kontrolliert absenken, bis die Schultern auf Ellbogenhöhe sind.", "Hochdrücken und oben wieder leicht ausdrehen."], back: "Körper als Einheit, Schultern weg von den Ohren.", easier: "Stütz an den Ringen halten oder Liegestütz." },
  { id: "bench_bar", name: "Langhantel-Bankdrücken", pattern: "hpush", tag: "Brust", req: ["bar", "bench"], weighted: true, sets: 3, repLow: 5, repHigh: 8, unit: "Wdh", muscle: "chest", muscleSecondary: "triceps", cue: "Schulterblätter zusammen, Füße fest, Stange zur unteren Brust.",
    steps: ["Flach auf die Bank, Schulterblätter zusammenziehen.", "Stange aus der Ablage, über der Brust halten.", "Kontrolliert zur unteren Brust senken, dann hochdrücken."], back: "Leichte natürliche Rückenspannung, Po bleibt auf der Bank.", easier: "Kurzhanteln oder weniger Gewicht." },
  { id: "bench_incline", name: "Schrägbankdrücken (Langhantel)", pattern: "hpush", tag: "Obere Brust", req: ["bar", "bench"], weighted: true, sets: 3, repLow: 6, repHigh: 10, unit: "Wdh", muscle: "chest", muscleSecondary: "shoulders", cue: "Bank ~30°, Stange zur oberen Brust.",
    steps: ["Bank auf etwa 30° stellen.", "Schulterblätter zusammen, Stange über der oberen Brust.", "Zur oberen Brust senken, dann hochdrücken."], back: "Fest angelehnt, kein Abheben aus der Bank.", easier: "Kurzhanteln, weniger Neigung." },
  { id: "bench_db", name: "Kurzhantel-Bankdrücken", pattern: "hpush", tag: "Brust", req: ["dumbbell", "bench"], weighted: true, sets: 3, repLow: 8, repHigh: 12, unit: "Wdh", muscle: "chest", muscleSecondary: "triceps", cue: "Auf der Bank, Hanteln über der Brust, tiefe Dehnung.",
    steps: ["Flach auf die Bank, Hanteln über der Brust.", "Kontrolliert bis auf Brusthöhe senken.", "Hochdrücken, oben nicht anschlagen."], back: "Schulterblätter stabil, Po auf der Bank.", easier: "Leichter oder Floor Press am Boden." },
  { id: "incline_db", name: "Schrägbankdrücken (Kurzhantel)", pattern: "hpush", tag: "Obere Brust", req: ["db", "bench"], weighted: true, sets: 3, repLow: 8, repHigh: 12, unit: "Wdh", muscle: "chest", muscleSecondary: "shoulders", cue: "Bank ~30°, Hanteln tief dehnen, obere Brust arbeitet.",
    steps: ["Bank auf ~30°, Hanteln über der oberen Brust.", "Tief absenken, Ellbogen ~45° zum Körper.", "Hochdrücken, Hanteln oben nicht zusammenschlagen."], back: "Fest anlehnen, Füße fest am Boden.", easier: "Flachbank oder leichter." },
  { id: "chest_press_machine", name: "Brustpresse (Maschine)", pattern: "hpush", tag: "Brust", req: ["machine"], weighted: true, sets: 3, repLow: 8, repHigh: 12, unit: "Wdh", muscle: "chest", muscleSecondary: "triceps", cue: "Griffe auf Brusthöhe, kontrolliert drücken und zurück.",
    steps: ["Sitz so einstellen, dass die Griffe auf Brusthöhe sind.", "Nach vorn drücken, Ellbogen nicht ganz strecken.", "Langsam zurück, Dehnung zulassen."], back: "Rücken bleibt am Polster — sichere Alternative zum Bankdrücken.", easier: "Weniger Gewicht, kleinerer Weg." },
  { id: "cable_fly", name: "Fliegende am Kabel", pattern: "hpush", tag: "Brust", req: ["cable"], weighted: true, sets: 3, repLow: 12, repHigh: 15, unit: "Wdh", muscle: "chest", cue: "Große Bögen vor der Brust, Ellbogen leicht gebeugt.",
    steps: ["Griffe auf Brusthöhe, Schritt nach vorn.", "Arme in weitem Bogen vor der Brust zusammenführen.", "Kontrolliert öffnen — die Dehnung ist der Reiz."], back: "Aufrechter fester Stand, Rumpf ruhig.", easier: "Weniger Gewicht, kleinerer Bogen." },
  { id: "db_fly", name: "Fliegende (Kurzhantel, Bank)", pattern: "hpush", tag: "Brust", req: ["db", "bench"], weighted: true, sets: 3, repLow: 10, repHigh: 15, unit: "Wdh", muscle: "chest", cue: "Leicht bleiben, weiter Bogen, tiefe Dehnung.",
    steps: ["Rücken auf die Bank, Hanteln über der Brust.", "Arme mit leicht gebeugten Ellbogen weit öffnen.", "Im Bogen wieder zusammenführen."], back: "Schulterblätter stabil, kein Hohlkreuz.", easier: "Deutlich leichter, kleinerer Bogen." },
  { id: "pec_deck", name: "Butterfly (Maschine)", pattern: "hpush", tag: "Brust", req: ["machine"], weighted: true, sets: 3, repLow: 10, repHigh: 15, unit: "Wdh", muscle: "chest", cue: "Ellbogen leicht gebeugt, vor der Brust zusammenführen.",
    steps: ["Sitz einstellen: Griffe auf Brusthöhe.", "Arme vor der Brust zusammenführen, kurz anspannen.", "Langsam öffnen, Dehnung spüren."], back: "Rücken bleibt fest am Polster.", easier: "Weniger Gewicht, Bewegungsweite verkleinern." },
  { id: "pushup_deficit", name: "Liegestütze erhöht (tiefer Dehnweg)", pattern: "hpush", tag: "Brust", req: ["box"], weighted: false, sets: 3, repLow: 8, repHigh: 15, unit: "Wdh", muscle: "chest", muscleSecondary: "triceps", cue: "Hände auf Erhöhungen — Brust darf tiefer als die Hände.",
    steps: ["Hände auf zwei Erhöhungen, Körper gerade.", "Brust tief zwischen die Hände absenken.", "Kraftvoll hochdrücken."], back: "Rumpf fest — die Tiefe fordert die Spannung extra.", easier: "Normale Liegestütze am Boden." },

  /* ── VPUSH — Drücken über Kopf ── */
  { id: "ohp_seat", name: "Schulterdrücken, sitzend", pattern: "vpush", tag: "Schultern", req: ["dumbbell"], weighted: true, sets: 3, repLow: 8, repHigh: 12, unit: "Wdh", muscle: "shoulders", muscleSecondary: "triceps", cue: "Aufrecht sitzen, Bauch fest, kein Hohlkreuz.",
    steps: ["Aufrecht sitzen, Hanteln auf Schulterhöhe.", "Hoch drücken bis fast gestreckt.", "Kontrolliert absenken."], back: "Bauch fest, nicht ins Hohlkreuz drücken.", easier: "Ein Arm abwechselnd, leichter." },
  { id: "ohp_stand", name: "Schulterdrücken, stehend", pattern: "vpush", tag: "Schultern", req: ["dumbbell"], weighted: true, sets: 3, repLow: 8, repHigh: 12, unit: "Wdh", muscle: "shoulders", muscleSecondary: "triceps", cue: "Po und Bauch fest, kein Ausweichen ins Kreuz.",
    steps: ["Stand hüftbreit, Hanteln auf Schulterhöhe.", "Hoch drücken, Rumpf fest.", "Kontrolliert absenken."], back: "Rippen unten, kein Hohlkreuz.", easier: "Sitzend ausführen." },
  { id: "pike_pushup", name: "Pike Liegestütz", pattern: "vpush", tag: "Schultern", req: ["none"], weighted: false, sets: 3, repLow: 6, repHigh: 12, unit: "Wdh", muscle: "shoulders", muscleSecondary: "triceps", cue: "Hüfte hoch, Kopf Richtung Boden.",
    steps: ["Umgekehrtes V, Hüfte hoch.", "Kopf Richtung Boden absenken.", "Hochdrücken."], back: "Rücken gerade, kontrolliert.", easier: "Hände erhöht." },
  { id: "ohp_bar", name: "Langhantel-Schulterdrücken", pattern: "vpush", tag: "Schultern", req: ["bar"], weighted: true, sets: 3, repLow: 5, repHigh: 8, unit: "Wdh", muscle: "shoulders", muscleSecondary: "triceps", cue: "Stange auf den vorderen Schultern, Po und Bauch fest, gerade nach oben.",
    steps: ["Stange auf den vorderen Schultern, schulterbreit greifen.", "Bauch und Po fest, Stange gerade über den Kopf drücken.", "Kopf leicht durchschieben, kontrolliert absenken."], back: "Kein Hohlkreuz — Rippen unten, Rumpf hart.", easier: "Sitzend mit Kurzhanteln." },
  { id: "arnold_press", name: "Arnold Press", pattern: "vpush", tag: "Schultern", req: ["db"], weighted: true, sets: 3, repLow: 8, repHigh: 12, unit: "Wdh", muscle: "shoulders", muscleSecondary: "triceps", cue: "Handflächen drehen beim Drücken von innen nach außen.",
    steps: ["Hanteln vor den Schultern, Handflächen zu dir.", "Beim Hochdrücken die Hände nach außen drehen.", "Auf dem Rückweg wieder eindrehen."], back: "Aufrecht, Rumpf fest, kein Hohlkreuz.", easier: "Sitzend, leichter." },
  { id: "shoulder_press_machine", name: "Schulterpresse (Maschine)", pattern: "vpush", tag: "Schultern", req: ["machine"], weighted: true, sets: 3, repLow: 8, repHigh: 12, unit: "Wdh", muscle: "shoulders", muscleSecondary: "triceps", cue: "Rücken ans Polster, gerade nach oben drücken.",
    steps: ["Sitz so einstellen, dass die Griffe auf Schulterhöhe starten.", "Nach oben drücken, Ellbogen nicht ganz strecken.", "Langsam zurück auf Schulterhöhe."], back: "Das Polster stützt den Rücken — saubere geführte Bahn.", easier: "Weniger Gewicht." },
  { id: "push_press", name: "Push Press (Langhantel)", pattern: "vpush", tag: "Schultern", req: ["bar"], weighted: true, sets: 3, repLow: 5, repHigh: 8, unit: "Wdh", muscle: "shoulders", muscleSecondary: "triceps", cue: "Kleiner Beinschwung hilft der Stange über den Kopf.",
    steps: ["Stange auf den vorderen Schultern.", "Kurz in die Knie dippen und explosiv strecken.", "Stange über Kopf ausdrücken, kontrolliert ablegen."], back: "Rumpf hart — der Impuls kommt aus den Beinen, nicht dem Kreuz.", easier: "Strikt drücken mit weniger Gewicht." },
  { id: "ohp_kb", name: "Einarmiges KB-Drücken", pattern: "vpush", tag: "Schultern", req: ["kb"], weighted: true, sets: 3, repLow: 6, repHigh: 10, unit: "Wdh", muscle: "shoulders", muscleSecondary: "core", cue: "Kugel in Rack-Position, Rumpf gegen die Einseitigkeit fest. Pro Arm.",
    steps: ["Kettlebell auf Schulterhöhe anlehnen (Rack).", "Gerade über den Kopf drücken.", "Kontrolliert zurück. Seite wechseln."], back: "Nicht zur Seite lehnen — die Mitte hält dagegen.", easier: "Leichter, beidarmig mit Kurzhanteln." },

  /* ── HPULL — horizontales Ziehen ── */
  { id: "row1", name: "Einarmiges Rudern, abgestützt", pattern: "hpull", tag: "Rücken", req: ["dumbbell"], weighted: true, sets: 3, repLow: 10, repHigh: 12, unit: "Wdh", muscle: "back", muscleSecondary: "biceps", cue: "Eine Hand abstützen, Rücken gerade. Pro Arm.",
    steps: ["Eine Hand auf Box/Stuhl, Rücken parallel zum Boden.", "Hantel eng zur Hüfte ziehen.", "Kontrolliert absenken. Seite wechseln."], back: "Grüne Linie absolut gerade, nicht rund.", easier: "Höher abstützen, leichter." },
  { id: "ringrow", name: "Ring-Rudern (Inverted Row)", pattern: "hpull", tag: "Rücken", req: ["rings"], weighted: false, sets: 3, repLow: 10, repHigh: 12, unit: "Wdh", muscle: "back", muscleSecondary: "biceps", cue: "Körper gerade wie ein Brett, Schulterblätter zusammen.",
    steps: ["Unter die Ringe, gestreckt aufhängen, Fersen am Boden.", "Brust zu den Ringen ziehen.", "Kontrolliert ablassen."], back: "Körper bleibt ein gerades Brett.", easier: "Aufrechter stellen." },
  { id: "band_row", name: "Rudern mit Band", pattern: "hpull", tag: "Rücken", req: ["bands"], weighted: false, sets: 3, repLow: 12, repHigh: 15, unit: "Wdh", muscle: "back", muscleSecondary: "biceps", cue: "Band fixieren, eng zum Bauch ziehen.",
    steps: ["Band auf Brusthöhe fixieren.", "Mit geradem Rücken zum Bauch ziehen, Ellbogen eng.", "Kontrolliert zurück."], back: "Aufrecht, nicht aus dem Rücken reißen.", easier: "Weniger Bandspannung." },
  { id: "row_bar", name: "Langhantelrudern", pattern: "hpull", tag: "Rücken", req: ["bar"], weighted: true, sets: 3, repLow: 6, repHigh: 10, unit: "Wdh", muscle: "back", muscleSecondary: "biceps", cue: "Oberkörper vorgebeugt, Rücken gerade, zur unteren Brust ziehen.", backCaution: true,
    steps: ["Hüfte zurück, Oberkörper etwa 45° vorgebeugt, Rücken neutral.", "Stange zum Bauch/zur unteren Brust ziehen, Ellbogen eng.", "Kontrolliert ablassen, Rücken bleibt fest."], back: "Vorgebeugte Position — Rücken bewusst gerade halten. Bei Reizung Einarm-Rudern abgestützt.", easier: "Leichter oder Einarmrudern abgestützt." },
  { id: "cable_row", name: "Rudern am Kabel, sitzend", pattern: "hpull", tag: "Rücken", req: ["cable"], weighted: true, sets: 3, repLow: 10, repHigh: 12, unit: "Wdh", muscle: "back", muscleSecondary: "biceps", cue: "Aufrecht sitzen, Griff zum Bauch, Schulterblätter zusammen.",
    steps: ["Füße abstützen, aufrecht hinsetzen.", "Griff zum Bauch ziehen, Ellbogen eng am Körper.", "Kontrolliert nach vorn nachlassen, Rücken bleibt lang."], back: "Aufrecht bleiben — nicht mit dem Kreuz nachschwingen.", easier: "Weniger Gewicht, kleinerer Weg." },
  { id: "chest_row_db", name: "Brustgestütztes KH-Rudern", pattern: "hpull", tag: "Rücken", req: ["db", "bench"], weighted: true, sets: 3, repLow: 10, repHigh: 12, unit: "Wdh", muscle: "back", muscleSecondary: "biceps", cue: "Brust auf die Schrägbank — der Rücken ist komplett raus.",
    steps: ["Bauchlings auf die Schrägbank legen.", "Hanteln hängen lassen, dann zur Hüfte ziehen.", "Langsam absenken, Schulterblätter öffnen lassen."], back: "Die Bank trägt den Oberkörper — beste Wahl bei empfindlichem Rücken.", easier: "Leichter, weniger Neigung." },
  { id: "row_machine", name: "Rudermaschine", pattern: "hpull", tag: "Rücken", req: ["machine"], weighted: true, sets: 3, repLow: 10, repHigh: 12, unit: "Wdh", muscle: "back", muscleSecondary: "biceps", cue: "Brust ans Polster, Ellbogen weit nach hinten ziehen.",
    steps: ["Brustpolster einstellen, Griffe fassen.", "Ellbogen nach hinten ziehen, Schulterblätter zusammen.", "Kontrolliert nach vorn nachlassen."], back: "Das Polster nimmt den Rücken raus — geführte, sichere Bahn.", easier: "Weniger Gewicht." },
  { id: "kb_row", name: "Kettlebell-Rudern", pattern: "hpull", tag: "Rücken", req: ["kb"], weighted: true, sets: 3, repLow: 10, repHigh: 12, unit: "Wdh", muscle: "back", muscleSecondary: "biceps", cue: "Abgestützt oder vorgebeugt, Kugel eng zur Hüfte. Pro Arm.",
    steps: ["Eine Hand abstützen, Rücken lang.", "Kettlebell eng am Körper zur Hüfte ziehen.", "Kontrolliert absenken. Seite wechseln."], back: "Rücken gerade, Rumpf ruhig.", easier: "Höher abstützen, leichter." },
  { id: "renegade_row", name: "Renegade Row", pattern: "hpull", tag: "Rücken & Core", req: ["db"], weighted: true, sets: 3, repLow: 8, repHigh: 10, unit: "Wdh", muscle: "back", muscleSecondary: "core", cue: "Liegestützposition auf den Hanteln, wechselseitig rudern.",
    steps: ["Liegestützposition, Hände auf den Hanteln.", "Eine Hantel zur Hüfte ziehen, Hüfte bleibt still.", "Absetzen, Seite wechseln."], back: "Becken nicht aufdrehen — die Mitte hält alles ruhig.", easier: "Breitere Beine, leichtere Hanteln." },
  { id: "shrug_db", name: "Schulterheben (Kurzhantel)", pattern: "hpull", tag: "Nacken & Trapez", req: ["db"], weighted: true, sets: 3, repLow: 12, repHigh: 15, unit: "Wdh", muscle: "back", muscleSecondary: "forearms", cue: "Schultern gerade nach oben ziehen, oben kurz halten.",
    steps: ["Hanteln seitlich hängen lassen.", "Schultern Richtung Ohren ziehen — Arme bleiben lang.", "Langsam absenken, Dehnung zulassen."], back: "Aufrecht, nicht mit dem Kreuz nachhelfen.", easier: "Leichter, langsamer." },

  /* ── VPULL — vertikales Ziehen ── */
  { id: "pullup", name: "Klimmzüge", pattern: "vpull", tag: "Rücken", req: ["pullup"], weighted: false, sets: 3, repLow: 6, repHigh: 10, unit: "Wdh", muscle: "back", muscleSecondary: "biceps", cue: "Schulterblätter runter, sauber hoch. Band als Hilfe.",
    steps: ["Etwas weiter als schulterbreit greifen.", "Hochziehen bis Kinn über die Stange.", "Kontrolliert ablassen."], back: "Hängen entlastet die Wirbelsäule, nicht pendeln.", easier: "Negativ oder mit Band." },
  { id: "chinup", name: "Chin-ups (Untergriff)", pattern: "vpull", tag: "Rücken & Bizeps", req: ["pullup"], weighted: false, sets: 3, repLow: 6, repHigh: 10, unit: "Wdh", muscle: "back", muscleSecondary: "biceps", cue: "Untergriff schulterbreit, sauber hoch.",
    steps: ["Untergriff, schulterbreit.", "Hochziehen bis Kinn über die Stange.", "Kontrolliert ablassen."], back: "Nicht ins Hohlkreuz schwingen.", easier: "Negativ oder mit Band." },
  { id: "band_pulldown", name: "Latzug mit Band", pattern: "vpull", tag: "Rücken", req: ["bands"], weighted: false, sets: 3, repLow: 12, repHigh: 15, unit: "Wdh", muscle: "back", muscleSecondary: "biceps", cue: "Band hoch fixieren, zur Brust ziehen.",
    steps: ["Band über Kopf fixieren.", "Ellbogen nach unten-außen zur Brust ziehen.", "Kontrolliert zurück."], back: "Aufrecht, Rumpf stabil.", easier: "Weniger Spannung." },
  { id: "lat_pulldown", name: "Latzug am Kabel", pattern: "vpull", tag: "Rücken", req: ["cable"], weighted: true, sets: 3, repLow: 8, repHigh: 12, unit: "Wdh", muscle: "back", muscleSecondary: "biceps", cue: "Stange zur oberen Brust, Ellbogen nach unten-außen.",
    steps: ["Oberschenkel unter die Polster, weit greifen.", "Stange zur oberen Brust ziehen, Brust auf.", "Langsam nach oben nachlassen, Lat dehnen."], back: "Leicht zurückgelehnt, ohne Schwung.", easier: "Weniger Gewicht, engerer Griff." },
  { id: "straight_arm_pulldown", name: "Überzüge am Kabel (gestreckt)", pattern: "vpull", tag: "Rücken", req: ["cable"], weighted: true, sets: 3, repLow: 12, repHigh: 15, unit: "Wdh", muscle: "back", cue: "Arme fast gestreckt, Stange im Bogen zur Hüfte.",
    steps: ["Hoch eingehängtes Kabel, leicht vorbeugen.", "Mit langen Armen die Stange zur Hüfte führen.", "Kontrolliert nach oben, Lat lang werden lassen."], back: "Rumpf fest, Bewegung nur aus den Schultern.", easier: "Weniger Gewicht, Band statt Kabel." },
  { id: "pullup_negative", name: "Negativ-Klimmzüge", pattern: "vpull", tag: "Rücken", req: ["pullup"], weighted: false, sets: 3, repLow: 3, repHigh: 6, unit: "Wdh", muscle: "back", muscleSecondary: "biceps", cue: "Oben starten, so langsam wie möglich ablassen.",
    steps: ["Per Sprung oder Box in die obere Position.", "3–5 Sekunden kontrolliert ablassen.", "Unten kurz hängen, wieder hoch."], back: "Ruhig bleiben, nicht fallen lassen.", easier: "Schneller ablassen, weniger Wiederholungen." },
  { id: "scap_pullup", name: "Schulterblatt-Klimmzüge", pattern: "vpull", tag: "Rücken & Schulterblätter", req: ["pullup"], weighted: false, sets: 3, repLow: 8, repHigh: 12, unit: "Wdh", muscle: "back", cue: "Arme gestreckt lassen — nur die Schulterblätter ziehen.",
    steps: ["Gestreckt an die Stange hängen.", "Schulterblätter nach unten ziehen, Brust leicht heben.", "Wieder lang werden lassen."], back: "Kleines, präzises Movement — die Basis jedes Klimmzugs.", easier: "Füße auf einer Box abstützen." },
  { id: "pullover_db", name: "Überzüge (Kurzhantel, Bank)", pattern: "vpull", tag: "Rücken & Brust", req: ["db", "bench"], weighted: true, sets: 3, repLow: 10, repHigh: 15, unit: "Wdh", muscle: "back", muscleSecondary: "chest", cue: "Eine Hantel im Bogen hinter den Kopf, Dehnung spüren.",
    steps: ["Rücken auf die Bank, eine Hantel über der Brust.", "Mit leicht gebeugten Armen hinter den Kopf senken.", "Im Bogen zurück über die Brust."], back: "Rippen unten, kein Hohlkreuz beim Absenken.", easier: "Leichter, kleinerer Bogen." },

  /* ── ARM — Bizeps, Trizeps, Unterarme ── */
  { id: "curl", name: "Bizeps Curls", pattern: "arm", tag: "Bizeps", req: ["weight"], weighted: true, sets: 3, repLow: 10, repHigh: 12, unit: "Wdh", muscle: "biceps", cue: "Ellbogen fix, kein Schwung aus dem Rücken.",
    steps: ["Aufrecht, Hanteln seitlich.", "Unterarme hochcurlen, Ellbogen fix.", "Langsam ablassen."], back: "Kein Schwung aus Rücken/Hüfte.", easier: "Im Sitzen." },
  { id: "hammer_curl", name: "Hammer Curls", pattern: "arm", tag: "Bizeps", req: ["dumbbell"], weighted: true, sets: 3, repLow: 10, repHigh: 12, unit: "Wdh", muscle: "biceps", muscleSecondary: "forearms", cue: "Neutralgriff, Ellbogen fix.",
    steps: ["Hanteln im Hammergriff seitlich.", "Hochcurlen ohne Schwung.", "Langsam ablassen."], back: "Fester Stand, ruhige Mitte.", easier: "Im Sitzen, leichter." },
  { id: "tri_oh", name: "Trizeps über Kopf (KH)", pattern: "arm", tag: "Trizeps", req: ["dumbbell"], weighted: true, sets: 3, repLow: 10, repHigh: 15, unit: "Wdh", muscle: "triceps", cue: "Ellbogen eng, nur Unterarm bewegt.",
    steps: ["Eine Hantel über dem Kopf, beide Hände.", "Hinter den Kopf absenken, Ellbogen eng.", "Wieder strecken."], back: "Rippen unten, kein Hohlkreuz.", easier: "Leichter, sitzend." },
  { id: "incline_curl", name: "Schrägbank-Curls", pattern: "arm", tag: "Bizeps", req: ["db", "bench"], weighted: true, sets: 3, repLow: 10, repHigh: 12, unit: "Wdh", muscle: "biceps", cue: "Zurückgelehnt hängen die Arme weit — Curl aus voller Dehnung.",
    steps: ["Bank auf ~45–60°, zurücklehnen.", "Arme hängen lassen, aus der Dehnung hochcurlen.", "Langsam ganz zurück."], back: "Rücken bleibt an der Bank, Schultern unten.", easier: "Steiler stellen, leichter." },
  { id: "concentration_curl", name: "Konzentrations-Curls", pattern: "arm", tag: "Bizeps", req: ["db"], weighted: true, sets: 3, repLow: 10, repHigh: 12, unit: "Wdh", muscle: "biceps", cue: "Ellbogen am Oberschenkel abgestützt, streng curlen. Pro Arm.",
    steps: ["Sitzen, Ellbogen an die Oberschenkel-Innenseite.", "Streng hochcurlen, oben anspannen.", "Sehr langsam ablassen. Seite wechseln."], back: "Aufrecht sitzen, Bewegung nur im Unterarm.", easier: "Leichter, weniger Wiederholungen." },
  { id: "cable_curl", name: "Bizeps am Kabel", pattern: "arm", tag: "Bizeps", req: ["cable"], weighted: true, sets: 3, repLow: 10, repHigh: 15, unit: "Wdh", muscle: "biceps", cue: "Konstante Spannung — das Kabel lässt nie locker.",
    steps: ["Kabel tief einhängen, Griff fassen.", "Ellbogen fix, hochcurlen.", "Langsam gegen den Zug ablassen."], back: "Aufrecht, nicht nach hinten lehnen.", easier: "Weniger Gewicht." },
  { id: "curl_bar", name: "Langhantel-Curls", pattern: "arm", tag: "Bizeps", req: ["bar"], weighted: true, sets: 3, repLow: 8, repHigh: 12, unit: "Wdh", muscle: "biceps", muscleSecondary: "forearms", cue: "Schulterbreiter Griff, Ellbogen bleiben am Körper.",
    steps: ["Stange schulterbreit im Untergriff.", "Hochcurlen ohne Schwung.", "Langsam ablassen, Arme fast strecken."], back: "Rumpf fest — kein Anschwingen aus dem Kreuz.", easier: "Kurzhanteln oder leichter." },
  { id: "skull_crusher", name: "French Press (liegend)", pattern: "arm", tag: "Trizeps", req: ["db", "bench"], weighted: true, sets: 3, repLow: 10, repHigh: 12, unit: "Wdh", muscle: "triceps", cue: "Hanteln zur Stirn absenken, Ellbogen zeigen zur Decke.",
    steps: ["Rücken auf die Bank, Hanteln über der Brust.", "Nur die Unterarme beugen — Hanteln neben den Kopf.", "Wieder strecken, Ellbogen bleiben stehen."], back: "Unterer Rücken bleibt an der Bank.", easier: "Leichter, am Boden liegend." },
  { id: "pushdown", name: "Trizepsdrücken am Kabel", pattern: "arm", tag: "Trizeps", req: ["cable"], weighted: true, sets: 3, repLow: 10, repHigh: 15, unit: "Wdh", muscle: "triceps", cue: "Ellbogen am Körper fixiert, nur die Unterarme strecken.",
    steps: ["Kabel hoch einhängen, Griff oder Seil fassen.", "Unterarme nach unten strecken, oben nicht mitschwingen.", "Langsam zurück bis ~90°."], back: "Aufrecht, leicht vorgelehnt, Rumpf fest.", easier: "Weniger Gewicht, Band statt Kabel." },
  { id: "tri_cable_oh", name: "Trizeps über Kopf am Kabel", pattern: "arm", tag: "Trizeps", req: ["cable"], weighted: true, sets: 3, repLow: 10, repHigh: 15, unit: "Wdh", muscle: "triceps", cue: "Vom Kabel weggelehnt, Arme über Kopf strecken — lange Dehnung.",
    steps: ["Seil tief/mittig einhängen, wegdrehen und vorlehnen.", "Arme über Kopf nach vorn strecken.", "Langsam beugen, Dehnung hinter dem Kopf zulassen."], back: "Rumpf fest, kein Hohlkreuz trotz Überkopf-Position.", easier: "Weniger Gewicht, KH-Variante." },
  { id: "diamond_pushup", name: "Enge Liegestütze (Diamant)", pattern: "arm", tag: "Trizeps", req: ["none"], weighted: false, sets: 3, repLow: 8, repHigh: 15, unit: "Wdh", muscle: "triceps", muscleSecondary: "chest", cue: "Hände eng unter der Brust, Ellbogen bleiben am Körper.",
    steps: ["Hände eng zusammen (Dreieck) unter der Brust.", "Absenken, Ellbogen eng am Körper.", "Kraftvoll hochdrücken."], back: "Körperspannung wie beim normalen Liegestütz.", easier: "Knie absetzen oder Hände erhöht." },
  { id: "bench_dips", name: "Dips an der Bank", pattern: "arm", tag: "Trizeps", req: ["bench"], weighted: false, sets: 3, repLow: 8, repHigh: 15, unit: "Wdh", muscle: "triceps", muscleSecondary: "shoulders", cue: "Hände hinter dir auf der Bank, eng am Körper absenken.",
    steps: ["Rücken zur Bank, Hände auf die Kante.", "Ellbogen nach hinten beugen, Körper absenken.", "Kraftvoll hochdrücken."], back: "Schultern unten lassen, nicht zu tief sinken.", easier: "Füße näher am Körper." },
  { id: "wrist_curl", name: "Handgelenk-Curls", pattern: "arm", tag: "Unterarme", req: ["db"], weighted: true, sets: 3, repLow: 15, repHigh: 20, unit: "Wdh", muscle: "forearms", cue: "Unterarme aufgelegt, nur die Handgelenke bewegen.",
    steps: ["Unterarme auf die Oberschenkel, Handflächen nach oben.", "Handgelenke hochcurlen.", "Langsam weit absenken."], back: "Aufrecht sitzen, kleine ruhige Bewegung.", easier: "Leichter, beidhändig eine Hantel." },
  { id: "reverse_curl", name: "Reverse Curls (Obergriff)", pattern: "arm", tag: "Unterarme", req: ["db"], weighted: true, sets: 3, repLow: 10, repHigh: 15, unit: "Wdh", muscle: "forearms", muscleSecondary: "biceps", cue: "Obergriff — die Unterarm-Oberseite arbeitet.",
    steps: ["Hanteln im Obergriff vor den Oberschenkeln.", "Hochcurlen, Handrücken zeigen nach oben.", "Langsam ablassen."], back: "Ellbogen fix, kein Schwung.", easier: "Leichter als normale Curls wählen." },

  /* ── LATERAL — Schulter-Feinarbeit ── */
  { id: "lateral", name: "Seitheben", pattern: "lateral", tag: "Schultern", req: ["dumbbell"], weighted: true, sets: 3, repLow: 12, repHigh: 15, unit: "Wdh", muscle: "shoulders", cue: "Leicht und sauber, Ellbogen führen, kein Schwung.",
    steps: ["Aufrecht, leichte Hanteln seitlich.", "Arme bis Schulterhöhe heben.", "Langsam ablassen."], back: "Kein Schwung, fester Stand.", easier: "Im Sitzen, sehr leicht." },
  { id: "face_pull", name: "Face Pull (Band)", pattern: "lateral", tag: "Hintere Schulter", req: ["bands"], weighted: false, sets: 3, repLow: 15, repHigh: 20, unit: "Wdh", muscle: "shoulders", muscleSecondary: "back", cue: "Band zum Gesicht ziehen, Schultern öffnen.",
    steps: ["Band auf Kopfhöhe fixieren.", "Zum Gesicht ziehen, Ellbogen hoch.", "Kontrolliert zurück."], back: "Aufrecht, Rumpf stabil.", easier: "Weniger Spannung." },
  { id: "cable_lateral", name: "Seitheben am Kabel", pattern: "lateral", tag: "Schultern", req: ["cable"], weighted: true, sets: 3, repLow: 12, repHigh: 15, unit: "Wdh", muscle: "shoulders", cue: "Kabel tief, Spannung schon unten — sauber zur Seite. Pro Arm.",
    steps: ["Seitlich zum tief eingehängten Kabel stehen.", "Arm bis Schulterhöhe zur Seite heben.", "Langsam gegen den Zug ablassen. Seite wechseln."], back: "Aufrecht, nicht mit der Hüfte anschieben.", easier: "Weniger Gewicht, Band statt Kabel." },
  { id: "band_lateral", name: "Seitheben mit Band", pattern: "lateral", tag: "Schultern", req: ["bands"], weighted: false, sets: 3, repLow: 15, repHigh: 20, unit: "Wdh", muscle: "shoulders", cue: "Auf das Band stellen, beide Arme zur Seite.",
    steps: ["Mittig auf das Band stellen, Enden greifen.", "Arme bis Schulterhöhe heben.", "Langsam ablassen."], back: "Rumpf ruhig, Schultern weg von den Ohren.", easier: "Weniger Vorspannung, einarmig." },
  { id: "reverse_fly_db", name: "Reverse Flys (vorgebeugt)", pattern: "lateral", tag: "Hintere Schulter", req: ["db"], weighted: true, sets: 3, repLow: 12, repHigh: 15, unit: "Wdh", muscle: "shoulders", muscleSecondary: "back", cue: "Vorgebeugt, leichte Hanteln weit zur Seite öffnen.",
    steps: ["Hüfte zurück, Oberkörper fast waagerecht, Rücken lang.", "Arme mit leicht gebeugten Ellbogen zur Seite heben.", "Langsam zurück, ohne Schwung."], back: "Rücken gerade halten — sehr leichtes Gewicht wählen.", easier: "Sitzend vorgebeugt oder an der Maschine." },
  { id: "reverse_fly_machine", name: "Reverse Butterfly (Maschine)", pattern: "lateral", tag: "Hintere Schulter", req: ["machine"], weighted: true, sets: 3, repLow: 12, repHigh: 15, unit: "Wdh", muscle: "shoulders", muscleSecondary: "back", cue: "Brust ans Polster, Arme weit nach hinten öffnen.",
    steps: ["Sitz einstellen, Brust ans Polster.", "Arme auf Schulterhöhe weit nach hinten führen.", "Kontrolliert zurück, Spannung halten."], back: "Das Polster stützt — Rücken komplett entlastet.", easier: "Weniger Gewicht." },
  { id: "front_raise", name: "Frontheben", pattern: "lateral", tag: "Vordere Schulter", req: ["db"], weighted: true, sets: 3, repLow: 10, repHigh: 15, unit: "Wdh", muscle: "shoulders", cue: "Hanteln gestreckt nach vorn bis Schulterhöhe.",
    steps: ["Hanteln vor den Oberschenkeln.", "Gestreckte Arme nach vorn auf Schulterhöhe heben.", "Langsam ablassen."], back: "Nicht zurücklehnen — Rumpf hält dagegen.", easier: "Leichter, abwechselnd einarmig." },
  { id: "upright_row", name: "Aufrechtes Rudern", pattern: "lateral", tag: "Schultern & Trapez", req: ["db"], weighted: true, sets: 3, repLow: 10, repHigh: 12, unit: "Wdh", muscle: "shoulders", muscleSecondary: "back", cue: "Hanteln eng am Körper hochziehen, Ellbogen führen.",
    steps: ["Hanteln vor den Oberschenkeln.", "Eng am Körper bis Brusthöhe ziehen, Ellbogen hoch.", "Langsam ablassen."], back: "Nur bis Brusthöhe — schulterfreundlicher als bis zum Kinn.", easier: "Leichter, kleinerer Weg." },
  { id: "face_pull_cable", name: "Face Pull am Kabel", pattern: "lateral", tag: "Hintere Schulter", req: ["cable"], weighted: true, sets: 3, repLow: 15, repHigh: 20, unit: "Wdh", muscle: "shoulders", muscleSecondary: "back", cue: "Seil auf Gesichtshöhe, zum Gesicht ziehen und außen rotieren.",
    steps: ["Seil auf Kopfhöhe einhängen, Enden greifen.", "Zum Gesicht ziehen, Hände neben die Ohren.", "Kontrolliert zurück."], back: "Aufrecht, Schulterblätter aktiv zusammen.", easier: "Weniger Gewicht, Band-Variante." },
  { id: "rear_delt_row", name: "Rudern für die hintere Schulter", pattern: "lateral", tag: "Hintere Schulter", req: ["db"], weighted: true, sets: 3, repLow: 12, repHigh: 15, unit: "Wdh", muscle: "shoulders", muscleSecondary: "back", cue: "Vorgebeugt, Ellbogen weit nach außen ziehen.",
    steps: ["Vorbeugen wie beim Rudern, Rücken lang.", "Hanteln mit WEITEN Ellbogen auf Brusthöhe ziehen.", "Langsam absenken."], back: "Rücken gerade, leichtes Gewicht.", easier: "Brustgestützt auf der Schrägbank." },

  /* ── CORE — Rumpf & Rücken-Stabilisatoren ── */
  { id: "plank", name: "Unterarmstütz (Plank)", pattern: "core", tag: "Core", req: ["none"], weighted: false, sets: 3, repLow: 30, repHigh: 45, unit: "Sek", muscle: "core", cue: "Gerade Linie, Bauch und Po fest.",
    steps: ["Unterarme unter den Schultern.", "Körper gerade von Kopf bis Ferse.", "Halten, ruhig atmen."], back: "Bauch und Po fest, Hüfte nicht durchhängen.", easier: "Auf den Knien." },
  { id: "sideplank", name: "Side Plank", pattern: "core", tag: "Rücken-Stabi", req: ["none"], weighted: false, sets: 3, repLow: 20, repHigh: 40, unit: "Sek", muscle: "core", cue: "Gerade Linie, Hüfte oben. Pro Seite.", backStabilizer: true,
    steps: ["Auf eine Seite, Unterarm unter der Schulter.", "Hüfte hoch, Körper gerade.", "Halten, Seite wechseln."], back: "Seitliche Rumpfstabilität, gerade Linie.", easier: "Knie ablegen." },
  { id: "pallof", name: "Pallof Press (Band)", pattern: "core", tag: "Rücken-Stabi", req: ["bands"], weighted: false, sets: 3, repLow: 10, repHigh: 12, unit: "Wdh", muscle: "core", cue: "Arme rausdrücken, gegen Rotation stabil. Pro Seite.", backStabilizer: true,
    steps: ["Seitlich zum fixierten Band, Band vor der Brust.", "Arme gerade nach vorne drücken.", "Halten, zurück. Seite wechseln."], back: "Rumpf gegen die Verdrehung stabil. Schützt den unteren Rücken.", easier: "Weniger Spannung, näher zum Anker." },
  { id: "birddog", name: "Bird Dog", pattern: "core", tag: "Rücken-Stabi", req: ["none"], weighted: false, sets: 3, repLow: 8, repHigh: 12, unit: "Wdh", muscle: "core", cue: "Gegenüberliegende Hand und Bein strecken, Rumpf ruhig.", backStabilizer: true,
    steps: ["Vierfüßlerstand, Rücken neutral.", "Rechten Arm und linkes Bein strecken.", "Kurz halten, wechseln."], back: "Becken stabil, kein Durchhängen. Top für den unteren Rücken.", easier: "Nur Bein oder nur Arm." },
  { id: "deadbug", name: "Dead Bug", pattern: "core", tag: "Rücken-Stabi", req: ["none"], weighted: false, sets: 3, repLow: 8, repHigh: 12, unit: "Wdh", muscle: "core", cue: "Unterer Rücken bleibt am Boden.", backStabilizer: true,
    steps: ["Auf dem Rücken, Arme und Beine in die Luft.", "Gegenüberliegenden Arm und Bein absenken.", "Zurück, Seite wechseln."], back: "Lende gegen den Boden gedrückt halten.", easier: "Nur Beine bewegen." },
  { id: "gb_march", name: "Glute Bridge March", pattern: "core", tag: "Rücken-Stabi", req: ["none"], weighted: false, sets: 3, repLow: 10, repHigh: 16, unit: "Wdh", muscle: "core", muscleSecondary: "glutes", cue: "Hüfte oben halten, abwechselnd Knie heben.", backStabilizer: true,
    steps: ["In die Brücke, Hüfte hoch.", "Ein Knie zur Brust heben, Becken stabil.", "Wechseln, Hüfte bleibt oben."], back: "Becken nicht kippen, Po fest.", easier: "Ohne Marsch, nur Brücke halten." },
  { id: "suitcase", name: "Koffertragen (Suitcase Carry)", pattern: "core", tag: "Rücken-Stabi", req: ["weight"], weighted: false, sets: 3, repLow: 20, repHigh: 40, unit: "Sek", muscle: "core", muscleSecondary: "forearms", cue: "Schwere Hantel einseitig, aufrecht gehen.", backStabilizer: true,
    steps: ["Eine schwere Hantel in einer Hand.", "Aufrecht gehen, nicht zur Seite kippen.", "Zeit pro Seite."], back: "Rumpf gegen das seitliche Ziehen stabil halten.", easier: "Leichter, kürzere Zeit." },
  { id: "hollow_hold", name: "Hollow Hold", pattern: "core", tag: "Core", req: ["none"], weighted: false, sets: 3, repLow: 20, repHigh: 40, unit: "Sek", muscle: "core", cue: "Lende in den Boden, Arme und Beine lang halten.",
    steps: ["Auf den Rücken, Lende fest in den Boden drücken.", "Schultern und Beine leicht abheben.", "Position halten, ruhig atmen."], back: "Die Lende darf nie abheben — sonst Beine höher.", easier: "Knie anwinkeln, Arme seitlich." },
  { id: "hanging_knee_raise", name: "Hängendes Knieheben", pattern: "core", tag: "Core", req: ["pullup"], weighted: false, sets: 3, repLow: 8, repHigh: 12, unit: "Wdh", muscle: "core", muscleSecondary: "forearms", cue: "Ruhig hängen, Knie kontrolliert zur Brust.",
    steps: ["An die Stange hängen, Schultern aktiv.", "Knie kontrolliert Richtung Brust ziehen.", "Langsam absenken, nicht pendeln."], back: "Das Hängen entlastet — kein Schwung, kein Hohlkreuz.", easier: "Nur Knie anheben, kleinerer Weg." },
  { id: "cable_chop", name: "Holzfäller am Kabel", pattern: "core", tag: "Core", req: ["cable"], weighted: true, sets: 3, repLow: 10, repHigh: 12, unit: "Wdh", muscle: "core", cue: "Diagonal von oben nach unten ziehen, Arme lang. Pro Seite.",
    steps: ["Kabel hoch einhängen, seitlich stehen.", "Diagonal zur Gegenhüfte ziehen, Rumpf rotiert kontrolliert.", "Langsam zurück. Seite wechseln."], back: "Bewegung aus der Körpermitte, nicht aus den Armen.", easier: "Weniger Gewicht, halber Weg." },
  { id: "db_chop", name: "Holzfäller (Kurzhantel)", pattern: "core", tag: "Core", req: ["weight"], weighted: true, sets: 3, repLow: 10, repHigh: 12, unit: "Wdh", muscle: "core", cue: "Diagonal von Schulter zu Gegenhüfte, Arme lang, Rumpf rotiert kontrolliert. Pro Seite.",
    steps: ["Gewicht mit beiden Händen über eine Schulter heben.", "Diagonal zur gegenüberliegenden Hüfte führen.", "Kontrolliert zurück nach oben. Seite wechseln."], back: "Rotation aus der Mitte — nicht aus der Lende reißen.", easier: "Leichter, halber Weg." },
  { id: "around_world", name: "Around the World", pattern: "core", tag: "Core & Schultern", req: ["weight"], weighted: true, sets: 3, repLow: 8, repHigh: 12, unit: "Wdh", muscle: "core", muscleSecondary: "shoulders", cue: "Gewicht in einem weiten Kreis um den Kopf führen — der Rumpf bleibt ruhig. Pro Richtung.",
    steps: ["Gewicht mit beiden Händen vor der Brust halten.", "In einem weiten, kontrollierten Kreis um den Kopf führen.", "Nach dem Satz die Richtung wechseln."], back: "Aufrecht bleiben, Rippen unten — nicht ins Hohlkreuz ausweichen.", easier: "Leichter, kleinere Kreise." },
  { id: "wipers", name: "Scheibenwischer (Beine seitlich)", pattern: "core", tag: "Core", req: ["none"], weighted: false, sets: 3, repLow: 8, repHigh: 12, unit: "Wdh", muscle: "core", backCaution: true, cue: "Beine gehoben, langsam von Seite zu Seite — Schultern bleiben am Boden.",
    steps: ["Auf den Rücken, Beine angewinkelt über der Hüfte heben.", "Beine kontrolliert zu einer Seite absenken, Schultern unten lassen.", "Über die Mitte zur anderen Seite."], back: "Klein und langsam bewegen, keine Schwünge — bei Reizung Dead Bug wählen.", easier: "Knie stärker anwinkeln, kleinerer Winkel." },
  { id: "reverse_crunch", name: "Reverse Crunch", pattern: "core", tag: "Core", req: ["none"], weighted: false, sets: 3, repLow: 10, repHigh: 15, unit: "Wdh", muscle: "core", cue: "Becken einrollen, Knie Richtung Brust — ohne Schwung.",
    steps: ["Auf den Rücken, Knie angewinkelt über der Hüfte.", "Becken vom Boden einrollen, Knie zur Brust ziehen.", "Langsam absenken, Spannung halten."], back: "Sanfter zur Lende als klassische Crunches — trotzdem ohne Schwung arbeiten.", easier: "Kleinerer Weg, Hände seitlich abstützen." },
  { id: "crunch", name: "Crunches", pattern: "core", tag: "Core", req: ["none"], weighted: false, sets: 3, repLow: 12, repHigh: 20, unit: "Wdh", muscle: "core", backCaution: true, cue: "Nur die Schulterblätter abheben, Blick zur Decke, Lende bleibt unten.",
    steps: ["Auf den Rücken, Füße aufgestellt, Hände an die Schläfen.", "Oberkörper einrollen, Schulterblätter abheben.", "Langsam ablegen — kein Zug am Nacken."], back: "Wiederholte Beugung — bei gereiztem Rücken lieber Dead Bug oder Plank.", easier: "Kleinerer Weg, Arme vor der Brust kreuzen." },
  { id: "russian_twist", name: "Russian Twist", pattern: "core", tag: "Core", req: ["none"], weighted: true, sets: 3, repLow: 12, repHigh: 16, unit: "Wdh", muscle: "core", backCaution: true, cue: "Angelehnt sitzen, Gewicht kontrolliert von Seite zu Seite.",
    steps: ["Sitzen, Oberkörper zurücklehnen, Rücken lang.", "Gewicht oder Hände kontrolliert zur Seite führen.", "Zur anderen Seite — ohne Schwung."], back: "Rücken lang lassen — bei Reizung lieber Pallof Press.", easier: "Füße am Boden lassen, ohne Gewicht." },
  { id: "mountain_climbers", name: "Mountain Climbers", pattern: "core", tag: "Core & Kondition", req: ["none"], weighted: false, sets: 3, repLow: 20, repHigh: 40, unit: "Sek", muscle: "core", cue: "Stützposition, Knie im Wechsel zügig zur Brust.",
    steps: ["Liegestützposition, Schultern über den Händen.", "Knie abwechselnd zur Brust ziehen.", "Hüfte tief halten, Tempo kontrolliert."], back: "Hüfte nicht hochschieben, Mitte bleibt fest.", easier: "Langsameres Tempo, Hände erhöht." },
  { id: "superman", name: "Rückenschwimmer (Superman)", pattern: "core", tag: "Rücken-Stabi", req: ["none"], weighted: false, sets: 3, repLow: 10, repHigh: 15, unit: "Wdh", muscle: "core", muscleSecondary: "back", backStabilizer: true, cue: "Bäuchlings Arme und Beine leicht heben, ruhig halten.",
    steps: ["Bäuchlings, Arme nach vorn gestreckt.", "Arme, Brust und Beine wenige Zentimeter heben.", "Kurz halten, langsam ablegen."], back: "Klein und kontrolliert heben — kein Reißen in die Überstreckung.", easier: "Nur Arme oder nur Beine heben." },
  { id: "farmer_carry", name: "Farmer's Walk", pattern: "core", tag: "Rücken-Stabi & Griff", req: ["weight"], weighted: false, sets: 3, repLow: 30, repHigh: 45, unit: "Sek", muscle: "core", muscleSecondary: "forearms", backStabilizer: true, cue: "Zwei schwere Gewichte, aufrecht und ruhig gehen.",
    steps: ["In jede Hand ein schweres Gewicht.", "Aufrecht gehen, Schultern hinten-unten.", "Ruhige Schritte bis die Zeit um ist."], back: "Aufrichtung gegen die Last — exzellent für Haltung und Griff.", easier: "Leichter, kürzere Strecke." },

  /* ── CALF — Waden ── */
  { id: "calf_raise_bw", name: "Wadenheben (Körpergewicht)", pattern: "calf", tag: "Waden", req: ["none"], weighted: false, sets: 3, repLow: 15, repHigh: 25, unit: "Wdh", muscle: "calves", cue: "Ganz hoch auf die Zehenspitzen, oben kurz halten.",
    steps: ["Aufrecht stehen, Fußballen belasten.", "So hoch wie möglich auf die Zehenspitzen.", "Langsam absenken, Ferse kurz Richtung Boden."], back: "Aufrecht, bei Bedarf an der Wand abstützen.", easier: "Beidbeinig mit Abstützen." },
  { id: "calf_raise_db", name: "Wadenheben mit Kurzhantel", pattern: "calf", tag: "Waden", req: ["db"], weighted: true, sets: 3, repLow: 10, repHigh: 15, unit: "Wdh", muscle: "calves", cue: "Hantel in einer Hand, langsam hoch und tief absenken.",
    steps: ["Hantel in einer Hand, andere Hand stützt.", "Hoch auf die Fußballen, oben anspannen.", "Sehr langsam und tief absenken."], back: "Aufrecht, Bewegung nur im Sprunggelenk.", easier: "Ohne Gewicht, beidbeinig." },
  { id: "calf_single", name: "Einbeiniges Wadenheben (Kante)", pattern: "calf", tag: "Waden", req: ["box"], weighted: false, sets: 3, repLow: 12, repHigh: 20, unit: "Wdh", muscle: "calves", cue: "Fußballen auf der Kante — die Ferse sinkt tief. Pro Bein.",
    steps: ["Fußballen auf eine Kante/Stufe stellen.", "Ferse tief unter die Kante sinken lassen.", "Kraftvoll ganz nach oben. Seite wechseln."], back: "Festhalten erlaubt — volle Bewegungsweite zählt.", easier: "Beidbeinig auf der Kante." },
  { id: "calf_seated", name: "Wadenheben sitzend (Maschine)", pattern: "calf", tag: "Waden", req: ["machine"], weighted: true, sets: 3, repLow: 12, repHigh: 15, unit: "Wdh", muscle: "calves", cue: "Polster auf den Knien — trifft den tiefen Wadenmuskel.",
    steps: ["Fußballen auf die Kante, Polster auf die Oberschenkel.", "Fersen tief absenken.", "Hoch auf die Zehenspitzen, oben halten."], back: "Aufrecht sitzen, ruhiges Tempo.", easier: "Weniger Gewicht." },

  /* ── CARDIO (Peloton / Bike) — geplant; die Ist-Aufzeichnung kommt aus Strava. ── */
  { id: "bike_zone2", name: "Peloton · Zone 2", pattern: "cardio", tag: "Cardio", req: ["bike"], weighted: false, sets: 1, repLow: 20, repHigh: 30, unit: "Min", cue: "Locker im Grundlagenbereich — du kannst dabei noch reden (Zone 2).",
    steps: ["Niedriger bis mittlerer Widerstand.", "Gleichmäßig treten, ~85–95 rpm.", "20–30 Min ruhig durchfahren."], back: "Aufrecht sitzen, Schultern locker.", easier: "Kürzer fahren, weniger Widerstand." },
  { id: "bike_intervals", name: "Peloton · Intervalle", pattern: "cardio", tag: "Cardio", req: ["bike"], weighted: false, sets: 1, repLow: 18, repHigh: 22, unit: "Min", cue: "Nach dem Einrollen 5×(1 Min hart / 1 Min locker), dann ausrollen.",
    steps: ["3 Min locker einrollen.", "5 Runden: 1 Min hart (hoch atmen), 1 Min locker.", "3 Min ausrollen."], back: "Im Sitzen fahren, Rumpf ruhig.", easier: "4 Runden statt 5, kürzere harte Phasen." },
  { id: "bike_finisher", name: "Peloton · Sprint-Finisher", pattern: "cardio", tag: "Cardio", req: ["bike"], weighted: false, sets: 1, repLow: 6, repHigh: 10, unit: "Min", cue: "Kurzer, knackiger Abschluss: 5×(20 s All-out / 40 s locker).",
    steps: ["1–2 Min locker antreten.", "5 Runden: 20 s Vollgas, 40 s locker.", "1 Min ausrollen."], back: "Sauber sitzen, nicht verkrampfen.", easier: "3 Runden, kürzere Sprints." },
  { id: "bike_recovery", name: "Peloton · Recovery Spin", pattern: "cardio", tag: "Cardio", req: ["bike"], weighted: false, sets: 1, repLow: 10, repHigh: 15, unit: "Min", cue: "Ganz locker drehen — fördert die Erholung, kein Ehrgeiz.",
    steps: ["Sehr niedriger Widerstand.", "Locker kurbeln, ruhig atmen.", "10–15 Min."], back: "Entspannt aufrecht.", easier: "Kürzer." },
];

export const TEMPLATE: Template[] = [
  { key: "A", name: "Ganzkörper A", focus: "Beine & Druck", slots: ["squat", "hpush", "hinge", "vpush", "core"] },
  { key: "B", name: "Ganzkörper B", focus: "Beine & Zug", slots: ["lunge", "vpull", "hpull", "arm", "core"] },
  { key: "C", name: "Ganzkörper C", focus: "Mix & Stabilität", slots: ["squat", "hpush", "hpull", "lateral", "core"] },
];

/** Optionaler Peloton/Cardio-Tag — startbar, aber NICHT in der A/B/C-Auto-Rotation. */
export const CARDIO_DAY: Template = {
  key: "peloton",
  name: "Peloton",
  focus: "Cardio",
  slots: ["cardio", "cardio"],
};

/** „Die Prüfung" — ATLAS-Testtag: nur die Kernmuster, Rampe zum schweren Satz. */
export const EXAM_DAY: Template = {
  key: "exam",
  name: "Die Prüfung",
  focus: "Maximalkraft",
  slots: ["squat", "hinge", "hpush", "vpull"],
};

/** „Rücken-Reset" — gewichtsfreie Stabi-Einheit für Tage, an denen der Rücken
 *  zwickt. Slots dienen nur Warmup/Anzeige; die Übungsauswahl ist kuratiert
 *  (resolveResetSession) statt Muster-rotiert. */
export const RESET_DAY: Template = {
  key: "reset",
  name: "Rücken-Reset",
  focus: "Stabilität ohne Last",
  slots: ["core", "hpush", "core", "squat", "core", "core"],
};

export const EQUIP_LIST: EquipItem[] = [
  { key: "db", label: "Kurzhanteln" }, { key: "kb", label: "Kettlebell" }, { key: "bar", label: "Langhantel" },
  { key: "pullup", label: "Klimmzugstange" }, { key: "rings", label: "Turnringe" }, { key: "bands", label: "Bänder" },
  { key: "box", label: "Erhöhung / Box" }, { key: "bench", label: "Hantelbank" },
  { key: "cable", label: "Kabelzug" }, { key: "machine", label: "Kraftgeräte" },
  { key: "bike", label: "Peloton / Bike" },
];

export const DEFAULT_EQUIP: EquipKey[] = ["db", "kb", "bar", "pullup", "rings", "bands", "box", "bench", "bike"];

/** Voll ausgestattetes Studio — Vorlage für ein zweites Gym-Profil. */
export const STUDIO_EQUIP: EquipKey[] = ["db", "kb", "bar", "pullup", "bands", "box", "bench", "cable", "machine", "bike"];

export const PATTERN_LABEL: Record<Pattern, string> = {
  squat: "Kniebeuge", lunge: "Ausfallschritt/Bein", hinge: "Hüfte/Gesäß", hpush: "Druck horizontal", vpush: "Druck über Kopf", hpull: "Zug horizontal", vpull: "Zug vertikal", arm: "Arme", lateral: "Schultern", core: "Core / Rücken-Stabi", calf: "Waden", cardio: "Cardio / Bike",
};

export const PROFILE: [string, string][] = [
  ["Ziel", "Muskelaufbau"],
  ["Frequenz", "3× pro Woche"],
  ["Dauer", "20–30 Min / Einheit"],
  ["Körper", "1,93 m · 90 kg"],
  ["Achtung", "Unterer Rücken schonen"],
];
